version: "1.0"
services: 
  bastion:
    tty: true
    build: 
      context: .
      dockerfile: DockerfileBastion
    container_name: bastion-server
    hostname: bastion
    privileged: true
    ports:
      - 22:22

  server-1:
    tty: true
    build: 
      context: .
      dockerfile: DockerfileServer
    container_name: server-1
    hostname: server-1
    privileged: true
  server-2:
    tty: true
    build: 
      context: .
      dockerfile: DockerfileServer
    container_name: server-2
    hostname: server-2
    privileged: true
  server-3:
    tty: true
    build: 
      context: .
      dockerfile: DockerfileServer
    container_name: server-3
    hostname: server-3
    privileged: true
    
  balanceador:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - server-1
      - server-2
      - server-3


 
    
